# Generated by Django 5.0.5 on 2024-05-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVUpload',
        ),
    ]
