# Generated by Django 5.0.5 on 2024-05-08 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('csv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='accounts.csvfile')),
            ],
        ),
    ]
